AWSTemplateFormatVersion: '2010-09-09'
Description: IAM role for GitHub Actions OIDC to allow minimal agent operations
Parameters:
  GitHubOwner:
    Type: String
    Description: GitHub owner/organization (owner or organization name)
  GitHubRepo:
    Type: String
    Description: GitHub repository name
  AgentArtifactsBucket:
    Type: String
    Description: Artifacts S3 bucket used by the agent
  AgentLockTable:
    Type: String
    Description: DynamoDB lock table name
  AgentQueueUrl:
    Type: String
    Description: SQS queue URL for job messages
  AgentQueueArn:
    Type: String
    Description: SQS queue ARN for policy attachments
  AgentOIDCProviderArn:
    Type: String
    Default: ""
    Description: ARN of an existing OIDC provider to use. If empty, the stack will attempt to create one.
  AgentOIDCProviderDomain:
    Type: String
    Default: ""
    Description: Optional domain for an existing OIDC provider (e.g. token.actions.githubusercontent.com). If provided, the template will build the provider ARN using the account id.
  AgentOIDCRoleArn:
    Type: String
    Default: ""
    Description: ARN of an existing GitHub OIDC role to use. If empty, the stack will create a new role named gh-actions-agent-role-<repo>.
  AgentOIDCRoleName:
    Type: String
    Default: ""
    Description: Name of an existing GitHub OIDC role to attach policies to (when using AgentOIDCRoleArn).
  AgentOIDCProviderHardcodedArn:
    Type: String
    Default: ""
    Description: "(Debug) Hardcoded OIDC provider ARN to use for federated principal (e.g. arn:aws:iam::970030241939:oidc-provider/token.actions.githubusercontent.com). Only used if provided."

Resources:
  GitHubOIDCProvider:
    Type: AWS::IAM::OpenIDConnectProvider
    Condition: CreateOIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
  GitHubOIDCRole:
    Type: AWS::IAM::Role
    Condition: CreateOIDCRole
    Properties:
      RoleName: !Sub "gh-actions-agent-role-${GitHubRepo}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !If
                - CreateOIDCProvider
                - !Ref GitHubOIDCProvider
                - !If
                  - ProvideOIDCProviderArn
                  - !Ref AgentOIDCProviderArn
                  - !If
                    - ProvideOIDCProviderHardcoded
                    - !Ref AgentOIDCProviderHardcodedArn
                    - !Ref AgentOIDCProviderDomain
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub "repo:${GitHubOwner}/${GitHubRepo}:*"
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      Policies:
        - PolicyName: AgentActionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${AgentArtifactsBucket}
                  - !Sub arn:aws:s3:::${AgentArtifactsBucket}/*
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                Resource: !Ref AgentQueueArn
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AgentLockTable}
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                Resource: '*'

  GitHubOIDCRolePolicy:
    Type: AWS::IAM::Policy
    Condition: AttachPolicyToExistingOIDCRole
    Properties:
      PolicyName: GitHubOIDCRolePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${AgentArtifactsBucket}
              - !Sub arn:aws:s3:::${AgentArtifactsBucket}/*
          - Effect: Allow
            Action:
              - sqs:SendMessage
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !Ref AgentQueueArn
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:DeleteItem
              - dynamodb:Query
            Resource: !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${AgentLockTable}
          - Effect: Allow
            Action:
              - bedrock:InvokeModel
            Resource: '*'
      Roles:
        - !Ref AgentOIDCRoleName

Outputs:
  GitHubOIDCRoleArn:
    Description: IAM role ARN for GitHub Actions to assume via OIDC
    Value: !If [CreateOIDCRole, !GetAtt GitHubOIDCRole.Arn, !Ref AgentOIDCRoleArn]
  ChosenOIDCProviderArn:
    Description: The OIDC provider ARN chosen by the template (created, supplied, or constructed from domain)
    Value: !If
      - CreateOIDCProvider
      - !GetAtt GitHubOIDCProvider.Arn
      - !If
        - ProvideOIDCProviderArn
        - !Ref AgentOIDCProviderArn
        - !If
          - ProvideOIDCProviderHardcoded
          - !Ref AgentOIDCProviderHardcodedArn
          - !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/${AgentOIDCProviderDomain}"

Conditions:
  CreateOIDCProvider: !Equals [!Ref AgentOIDCProviderArn, ""]
  ProvideOIDCProviderArn: !Not [!Equals [!Ref AgentOIDCProviderArn, ""]]
  # ProvideOIDCProviderDomain: removed — not required (domain param used directly)
  ProvideOIDCProviderHardcoded: !Not [!Equals [!Ref AgentOIDCProviderHardcodedArn, ""]]
  CreateOIDCRole: !Equals [!Ref AgentOIDCRoleArn, ""]
  AttachPolicyToExistingOIDCRole: !Not [!Equals [!Ref AgentOIDCRoleName, ""]]
