#!/usr/bin/env bash
set -eu

# agent-build.sh
# Expects ISSUE_NUMBER environment variable and relevant secrets set as env vars.

ISSUE_NUMBER=${1:-}
if [ -z "$ISSUE_NUMBER" ]; then
  echo "Usage: scripts/agent-build.sh ISSUE_NUMBER"
  exit 1
fi

REPO=${GITHUB_REPOSITORY:-}
if [ -z "$REPO" ]; then
  # Try to read fallback repo
  REPO=$(git config --get remote.origin.url | sed -n 's#.*github.com[:/]\([^/]*\)/\([^/.]*\).*#\1/\2#p')
fi

echo "Starting agent build for issue ${ISSUE_NUMBER} on ${REPO}"


# Invoke the Bedrock AgentCore (or the placeholder script) to build the feature
echo "Starting AgentCore invocation for issue ${ISSUE_NUMBER}"
AGENT_OUTPUT=$(bash scripts/agent-core-invoke.sh ${ISSUE_NUMBER} ${REPO} "${AGENTCORE_RUNTIME_ID:-}" "${AGENTCORE_ROLE_ARN:-}" 2>&1)
echo "AgentCore output:\n${AGENT_OUTPUT}"

# For now, simply commit the generated artifacts and open a PR with them
BRANCH=agent-runtime/issue-${ISSUE_NUMBER}-$(date +%s)
git checkout -b ${BRANCH}

ARTIFACTS_DIR="build/agent-artifacts/issue_${ISSUE_NUMBER}"
if [ -d "${ARTIFACTS_DIR}" ]; then
  git add "${ARTIFACTS_DIR}" || true
fi

AGENT_NOTE_FILE=AGENT_BUILD_issue_${ISSUE_NUMBER}.md
echo "Agent build for issue ${ISSUE_NUMBER}" > ${AGENT_NOTE_FILE}
echo "Timestamp: $(date --utc)" >> ${AGENT_NOTE_FILE}
echo "Agent runtime id: ${AGENTCORE_RUNTIME_ID:-not_set}" >> ${AGENT_NOTE_FILE}
echo "Agent core output: ${AGENT_OUTPUT}" >> ${AGENT_NOTE_FILE}

git add ${AGENT_NOTE_FILE}
git commit -m "chore: agent build for issue #${ISSUE_NUMBER} (placeholder artifacts)"

# Push branch
git push --set-upstream origin ${BRANCH}

# Create PR
PR_TITLE="Agent build: issue #${ISSUE_NUMBER}"
PR_BODY="This PR contains changes (artifacts) generated by the AgentCore builder for issue #${ISSUE_NUMBER}.\n\nAgent output:\n\n${AGENT_OUTPUT}"
gh pr create --title "${PR_TITLE}" --body "${PR_BODY}" --base main --head ${BRANCH} || echo "gh pr create failed"

echo "Agent build complete — PR created with branch ${BRANCH}"
