#!/usr/bin/env bash
set -eu

# agent-build.sh
# Expects ISSUE_NUMBER environment variable and relevant secrets set as env vars.

ISSUE_NUMBER=${1:-}
if [ -z "$ISSUE_NUMBER" ]; then
  echo "Usage: scripts/agent-build.sh ISSUE_NUMBER"
  exit 1
fi

REPO=${GITHUB_REPOSITORY:-}
if [ -z "$REPO" ]; then
  # Try to read fallback repo
  REPO=$(git config --get remote.origin.url | sed -n 's#.*github.com[:/]\([^/]*\)/\([^/.]*\).*#\1/\2#p')
fi

echo "Starting agent build for issue ${ISSUE_NUMBER} on ${REPO}"

# Create a branch name
BRANCH=agent-runtime/issue-${ISSUE_NUMBER}-$(date +%s)
git checkout -b ${BRANCH}

# Generate a simple change as a placeholder for the agent's work
AGENT_NOTE_FILE=AGENT_BUILD_issue_${ISSUE_NUMBER}.md
echo "Agent build for issue ${ISSUE_NUMBER}" > ${AGENT_NOTE_FILE}
echo "Timestamp: $(date --utc)" >> ${AGENT_NOTE_FILE}
echo "Agent runtime id: ${AGENTCORE_RUNTIME_ID:-not_set}" >> ${AGENT_NOTE_FILE}

git add ${AGENT_NOTE_FILE}
git commit -m "chore: agent build for issue #${ISSUE_NUMBER} (placeholder)"

# Push branch
git push --set-upstream origin ${BRANCH}

# Create PR
PR_TITLE="Agent build: issue #${ISSUE_NUMBER}"
PR_BODY="This PR contains changes generated by the Bedrock AgentCore builder for issue #${ISSUE_NUMBER}."
gh pr create --title "${PR_TITLE}" --body "${PR_BODY}" --base main --head ${BRANCH} || echo "gh pr create failed"

echo "Agent build placeholder complete — PR created with branch ${BRANCH}"
